name: hoth
channels:
- conda-forge
dependencies:
- python=3
- numpy
- scipy
- scikit-learn
- pandas
- matplotlib
- seaborn
- statsmodels
- h5py
- jupyter
- jupyter_contrib_nbextensions
- ipython
- ipykernel
- flake8
- pip
- pip:
  - tmuxp
  - coverage
  - future
  - yapf
  - isort
  - jedi
