name: cb
dependencies:
- alabaster=0.7.7=py27_0
- appnope=0.1.0=py27_0
- babel=2.2.0=py27_0
- backports_abc=0.4=py27_0
- bokeh=0.11.1=py27_0
- cycler=0.9.0=py27_0
- decorator=4.0.6=py27_0
- docutils=0.12=py27_0
- enum34=1.1.2=py27_0
- flake8=2.5.1=py27_0
- freetype=2.5.5=0
- funcsigs=0.4=py27_0
- futures=3.0.3=py27_0
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=2
- ipykernel=4.2.2=py27_0
- ipython=4.0.3=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.1.0=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- llvmlite=0.8.0=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mccabe=0.3.1=py27_0
- mistune=0.7.1=py27_0
- mkl=11.3.1=0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.1.0=py27_0
- numba=0.23.1=np110py27_0
- numexpr=2.4.6=np110py27_0
- numpy=1.10.4=py27_0
- openssl=1.0.2f=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- patsy=0.4.0=np110py27_0
- pep8=1.7.0=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=8.0.2=py27_0
- ptyprocess=0.5=py27_0
- pycosat=0.6.1=py27_0
- pycrypto=2.6.1=py27_0
- pyflakes=1.0.0=py27_0
- pygments=2.1=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- requests=2.9.1=py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.17.0=np110py27_0
- seaborn=0.7.0=py27_0
- setuptools=19.6.2=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.3.5=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np110py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - ipyparallel==5.0.0.dev0
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - pandoc==1.0.0a8
  - sh==1.11
  - sphinx-rtd-theme==0.1.9
  - tables==3.2.2
  - tifffile==0.7.0

